
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MADHUSHAN THARANGA
 */
public class SignUp extends javax.swing.JFrame {

    
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        accTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        occTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        pinTxt = new javax.swing.JPasswordField();
        dob = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        clrBtn = new javax.swing.JButton();
        canBtn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ATM SYSTEM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 160, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Your Sign Up Details ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        cancelBtn.setBackground(new java.awt.Color(0, 153, 153));
        cancelBtn.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("x");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Pin NO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("DOB");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Occupation");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Tel NO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Acount NO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Address");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        accTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accTxt.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.add(accTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 210, -1));

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 210, -1));

        telTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telTxt.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.add(telTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 210, -1));

        occTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        occTxt.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.add(occTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, -1));

        addressTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressTxt.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 210, -1));

        pinTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pinTxt.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.add(pinTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 210, -1));

        dob.setForeground(new java.awt.Color(0, 153, 153));
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 210, 30));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 590, 20));

        clrBtn.setBackground(new java.awt.Color(0, 153, 153));
        clrBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clrBtn.setForeground(new java.awt.Color(255, 255, 255));
        clrBtn.setText("Clear");
        clrBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clrBtnMouseClicked(evt);
            }
        });
        jPanel2.add(clrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        canBtn.setBackground(new java.awt.Color(0, 153, 153));
        canBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        canBtn.setForeground(new java.awt.Color(255, 255, 255));
        canBtn.setText("Cancel");
        canBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canBtnMouseClicked(evt);
            }
        });
        jPanel2.add(canBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        subBtn.setBackground(new java.awt.Color(0, 153, 153));
        subBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subBtn.setForeground(new java.awt.Color(255, 255, 255));
        subBtn.setText("Submit");
        subBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subBtnMouseClicked(evt);
            }
        });
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });
        jPanel2.add(subBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\MADHUSHAN THARANGA\\Pictures\\atm\\l8.gif")); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 590, 450));

        setSize(new java.awt.Dimension(590, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    MiniStatement St = null;
    
    private void clear(){
        nameTxt.setText("");
        addressTxt.setText("");
        dob.setDate(null);
        occTxt.setText("");
        telTxt.setText("");
        accTxt.setText("");
        pinTxt.setText("");
    }
    
    private void subBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subBtnMouseClicked
        // TODO add your handling code here:
        if(nameTxt.getText().isEmpty() || addressTxt.getText().isEmpty() || occTxt.getText().isEmpty() || telTxt.getText().isEmpty() || accTxt.getText().isEmpty() || pinTxt.getText().isEmpty() || dob.getDate().toString().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information");
        }
        else{
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","");
                PreparedStatement Add = con.prepareStatement("Insert Into client Value (?,?,?,?,?,?,?,?) ");
                Add.setString(1, nameTxt.getText());
                Add.setInt(2, Integer.valueOf(accTxt.getText()));
                Add.setInt(3, 0);
                Add.setString(4, addressTxt.getText());
                Add.setString(5, occTxt.getText());
                Add.setString(6, telTxt.getText());
                Add.setInt(7, Integer.valueOf(pinTxt.getText()));
                Add.setString(8, dob.getDate().toString());
                
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Account Saved");
                con.close();
                clear();
           
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_subBtnMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subBtnActionPerformed

    private void canBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canBtnMouseClicked
        // TODO add your handling code here:
        MainPage mp = new MainPage();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_canBtnMouseClicked

    private void clrBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrBtnMouseClicked
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clrBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accTxt;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton canBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clrBtn;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField occTxt;
    private javax.swing.JPasswordField pinTxt;
    private javax.swing.JButton subBtn;
    private javax.swing.JTextField telTxt;
    // End of variables declaration//GEN-END:variables
}
